// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8OtGSAiUoP1OzJ9OJU5v__81o47pWaNY',
    appId: '1:911443567546:web:39d3757a65c5ac51147383',
    messagingSenderId: '911443567546',
    projectId: 'language-mixing-app',
    authDomain: 'language-mixing-app.firebaseapp.com',
    storageBucket: 'language-mixing-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiESAQIx2-7LEpuhIrhQAfwtWydL_o200',
    appId: '1:911443567546:android:3a2a338174493e25147383',
    messagingSenderId: '911443567546',
    projectId: 'language-mixing-app',
    storageBucket: 'language-mixing-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtrmqW1mvqzF0UunwOuaoSjU1JDQ_C-YE',
    appId: '1:911443567546:ios:f805393004002bec147383',
    messagingSenderId: '911443567546',
    projectId: 'language-mixing-app',
    storageBucket: 'language-mixing-app.firebasestorage.app',
    iosBundleId: 'com.example.languageMixingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtrmqW1mvqzF0UunwOuaoSjU1JDQ_C-YE',
    appId: '1:911443567546:ios:f805393004002bec147383',
    messagingSenderId: '911443567546',
    projectId: 'language-mixing-app',
    storageBucket: 'language-mixing-app.firebasestorage.app',
    iosBundleId: 'com.example.languageMixingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8OtGSAiUoP1OzJ9OJU5v__81o47pWaNY',
    appId: '1:911443567546:web:2e691c0814549bdd147383',
    messagingSenderId: '911443567546',
    projectId: 'language-mixing-app',
    authDomain: 'language-mixing-app.firebaseapp.com',
    storageBucket: 'language-mixing-app.firebasestorage.app',
  );
}
